### ISSUE TITLE
Broken "All tags" link mcr.microsoft.com/vscode/devcontainers/python (Details, History, All tags)

### ISSUE THREAD

**Issue by basictheprogram** [devcontainers/images#1113]
https://hub.docker.com/r/microsoft/vscode-devcontainers

Click the "All tags" link 

mcr.microsoft.com/vscode/devcontainers/python (Details, History, All tags)

https://mcr.microsoft.com/v2/vscode/devcontainers/python-3/tags/list

The requested content does not exist.

HttpStatusCode: 404
ErrorCode: WebContentNotFound
RequestId : 377a1291-401e-0065-6f81-d0f9e9000000
TimeStamp : 2024-07-07T15:26:04.0601226Z

**Comment by bamurtaugh** [comment]
Thanks for filing! 

I believe this is expected as part of our deprecation of https://github.com/microsoft/vscode-dev-containers, but cc @samruddhikhandale in case I'm missing anything.

**Comment by samruddhikhandale** [comment]
Thanks for looping me in! 

@bamurtaugh We are continuing to dual publish to the old path, hence, the images are still valid.

@gauravsaini04 Can you help fix the link in MCR Docs? It should be https://mcr.microsoft.com/v2/vscode/devcontainers/python/tags/list instead of https://mcr.microsoft.com/v2/vscode/devcontainers/python-3/tags/list

**Comment by gauravsaini04** [comment]
hi @samruddhikhandale , have pushed changes in this [pr](https://github.com/microsoft/mcrdocs/pull/47498)
