### ISSUE TITLE
javascript-node yarn dependency bins not in path

### ISSUE THREAD

**Issue by joshbuker** [devcontainers/images#1169]
Commands like `yarn create cloudflare@latest kv-tutorial` will fail because the create-cloudflare bin is not in the devcontainer's PATH. This also means any other dependencies with executables must be ran prepended with `yarn exec` or they will fail.

This seems very odd behavior for the defacto node devcontainer image. Is there a simple workaround that isn't included in the default config?

**Comment by samruddhikhandale** [comment]
Hi 👋 

The issue you're encountering is due to the fact that the create-cloudflare binary (and other similar binaries) are not in the global PATH when using the default Node.js dev container image. This is because these binaries are typically installed locally within the project and not globally.

Workarounds

1. Use yarn exec: This is the recommended approach as it ensures that the correct version of the binary is used from the project's dependencies.
    - yarn exec create-cloudflare@latest kv-tutorial
2. Add node_modules/.bin to PATH: You can modify the PATH environment variable to include the local node_modules/.bin directory. This can be done in the devcontainer.json file

**Comment by joshbuker** [comment]
Thanks @samruddhikhandale!

This appears to work for me, although if there's a better way please let me know:
```json
"remoteEnv": {
  "PATH": "/workspaces/${localWorkspaceFolderBasename}/node_modules/.bin:${containerEnv:PATH}"
},
```

Would it be possible to add this to the default `devcontainer.json` configuration for node as a commented out code block?

**Comment by joshbuker** [comment]
I was going to add this via PR, but noticed the CLA. Not a fan considering the history of CLA rugpulls, so closing this issue as the workaround solves my use-case.
