### ISSUE TITLE
Question:  What determines which extensions are included

### ISSUE THREAD

**Issue by andez2000** [devcontainers/images#243]
I was running the following `devcontainer.json`:

```json
{
	"image": "mcr.microsoft.com/devcontainers/python:3.11",
	"customizations": {
		"vscode": {
			"extensions": [
			]
		}
	}
}
```

I am not specifying any extensions, however in the vscode container remote extensions I see the following are installed:

1. ESLint
2. isort
3. Jupyter
4. Jupyter Cell Tags
5. Jupyter Notebook Renderers
6. Jupyter Slide Show
7. Jupyter Keymap
8. Python

I am assuming that the image `mcr.microsoft.com/devcontainers/python:3.11` ships these extensions.  I was just after a little more information on where these come from.

**Comment by samruddhikhandale** [comment]
With a recent @devcontainers/cli change for images [metadata](https://containers.dev/implementors/spec/#metadata). The `customizations` (which specifies the `extensions`) are now passed down from image to the dev container.

For `mcr.microsoft.com/devcontainers/python:3.11` - The `Python` and `Pylance` extensions are added by the image's devcontainer.json [here](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/devcontainer.json#L41-L44) and others by The [Features](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/devcontainer.json#L6-L20). eg. `ESLint` is installed by the [Node Feature](https://github.com/devcontainers/features/blob/main/src/node/devcontainer-feature.json#L40).

Besides these three extensions, all others are installed due to extensions packs.

![image](https://user-images.githubusercontent.com/24955913/205702380-a6c4eb91-411e-4d5c-b8f2-f83f4b59685b.png)

![image](https://user-images.githubusercontent.com/24955913/205702482-ac027fea-2d61-4e33-9ef0-f45b8fa58637.png)

**Comment by samruddhikhandale** [comment]
Closing as answered the question!

**Comment by Uguudei** [comment]
Node is optional. it's not necessary for a python project. Therefore, ESLint should be optional too. 
I propose removing node features from Python and Miniconda images. Users should add them to their devcontainer.json if they need them. 

It is annoying to uninstall ESLint to see them again every time I rebuild the image. ESLint wasn't included previously in the image.

**Comment by Uguudei** [comment]
Please open this issue. Also, It is not a question, but a bug. The extensions shouldn't be installed when it's not necessary.

**Comment by samruddhikhandale** [comment]
> Given JavaScript front-end web client code written for use in conjunction with a Python back-end often requires the use of Node.js-based utilities to build, this container also includes nvm so that you can easily install Node.js.

For python and miniconda images, highlighting the thought behind installing `nvm` as mentioned in [this doc](https://github.com/devcontainers/images/tree/main/src/python#installing-nodejs). Currently, `nvm` is getting installed via Node Feature (with [version:none](https://github.com/devcontainers/images/blob/main/src/python/.devcontainer/devcontainer.json#L15)) which could be avoided. Opened https://github.com/devcontainers/images/issues/424

> It is annoying to uninstall ESLint to see them again every time I rebuild the image. ESLint wasn't included previously in the image.

I agree, this can be an issue, feel free to add your thoughts or upvote https://github.com/devcontainers/features/issues/386
