### ISSUE TITLE
mcr.microsoft.com/devcontainers/universal:2 for M1 Mac

### ISSUE THREAD

**Issue by hsm207** [devcontainers/images#545]
It would be great if `mcr.microsoft.com/devcontainers/universal:2` supports arm64 too. 

running `docker pull mcr.microsoft.com/devcontainers/universal:2` on an M1 mac gives:

> 2: Pulling from devcontainers/universal
> no matching manifest for linux/arm64/v8 in the manifest list entries

The use case is to run the given devcontainer in the  [semantic-kernel ](https://github.com/microsoft/semantic-kernel) project.

**Comment by samruddhikhandale** [comment]
Hi 👋 

The universal image installs [oryx](https://github.com/microsoft/Oryx) in [here](https://github.com/devcontainers/images/blob/main/src/universal/.devcontainer/devcontainer.json#L73) which does not support arm builds. Hence, we are unable to provide arm64 support for the universal image due to that dependency.

Once oryx starts supporting arm builds, we'd be able to support that architecture.

**Comment by samruddhikhandale** [comment]
@hsm207 We support arm64 for all other images, would using some other image help? (probably [c++](https://github.com/devcontainers/images/tree/main/src/cpp) or [python](https://github.com/devcontainers/images/tree/main/src/python))

**Comment by hsm207** [comment]
@samruddhikhandale thanks for looking into test. I'll try some other image.

**Comment by samruddhikhandale** [comment]
Thank you, let us know if you need any help!

**Comment by iemejia** [comment]
I think this issue is important enough to let it open to keep track of it. I created an issue in the oryx repo https://github.com/microsoft/Oryx/issues/2133
